# Generated by Django 3.2.9 on 2022-04-26 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dyaduser_last_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyadProfile',
            fields=[
                ('Profile_Description', models.CharField(default='BLANK', max_length=200, null=True)),
                ('Display_name', models.CharField(max_length=24)),
                ('Profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.dyaduser')),
            ],
        ),
        migrations.RemoveField(
            model_name='dyaduser',
            name='phone_number',
        ),
    ]
